name: allergy_free
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Inter
    fonts:
    - asset: fonts/Inter-font.ttf
    - asset: fonts/Inter-italic.ttf